package com.archdox.worker.domain;

public enum ArchDoxWorkerActionType {
    WORKER_CHAT_ADVANCE,
    CREATE_SITE,
    CREATE_REPORT,
    UPDATE_REPORT_STEP,
    SUBMIT_REPORT,
    RUN_PREFLIGHT_REVIEW,
    REQUEST_DOCUMENT_GENERATION,
    ENRICH_LEGAL_CHANGE_DIGEST
}
