package com.archdox.worker.domain;

public enum ArchDoxWorkerActionType {
    RUN_DOCUMENT_QA,
    RUN_LEGAL_REVIEW,
    RERUN_DOCUMENT_QA_WITH_STRONGER_MODEL,
    DRAFT_INSPECTION_LOG,
    FIND_EVIDENCE_GAPS,
    PREPARE_SUBMISSION_PACKAGE,
    WORKER_CHAT_ADVANCE,
    CREATE_SITE,
    CREATE_REPORT,
    UPDATE_REPORT_STEP,
    SUBMIT_REPORT,
    RUN_PREFLIGHT_REVIEW,
    REQUEST_DOCUMENT_GENERATION,
    REQUEST_HUMAN_REVIEW,
    APPROVE_DOCUMENT,
    FAIL_REVIEW
}
