package com.archdox.cloud.legal.dto;

import java.util.List;

public record LegalDomainBindingCoverageItemResponse(
        String catalogCode,
        Integer catalogVersion,
        String tradeCode,
        String tradeName,
        String processCode,
        String processName,
        String checklistItemCode,
        String checklistItemName,
        String basis,
        int activeBindingCount,
        int inactiveBindingCount,
        int autoGeneratedBindingCount,
        int manualBindingCount,
        List<LegalDomainBindingResponse> bindings
) {
    public LegalDomainBindingCoverageItemResponse {
        bindings = bindings == null ? List.of() : List.copyOf(bindings);
    }
}
