package com.archdox.cloud.legal.dto;

import java.util.List;

public record LegalDomainBindingCoverageResponse(
        String catalogCode,
        Integer catalogVersion,
        String catalogName,
        int catalogItemCount,
        int activeBoundItemCount,
        int missingItemCount,
        int inactiveOnlyItemCount,
        int totalBindingCount,
        int autoGeneratedBindingCount,
        int manualBindingCount,
        List<LegalDomainBindingCoverageItemResponse> missingItems,
        List<LegalDomainBindingCoverageItemResponse> items
) {
    public LegalDomainBindingCoverageResponse {
        missingItems = missingItems == null ? List.of() : List.copyOf(missingItems);
        items = items == null ? List.of() : List.copyOf(items);
    }
}
