-- V20 originally broadened experimental document workflow layouts.
-- ArchDox is now focused on construction supervision for the current product
-- phase. Fresh databases seed only construction supervision document types in
-- V19, and later construction-specific migrations refine those definitions.
-- Keep this migration as an intentionally empty compatibility step.
